### ISSUE TITLE
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'putText'

### ISSUE THREAD

**Issue by BCCWAI** [stereolabs/zed-pytorch#9]
(pytorch1) dh-ununtu-64@dhununtu64-HP-Z1-Entry-Tower-G5:~/zedcamera/zed-pytorch$ python zed_object_detection.py --config-file configs/caffe2/e2e_mask_rcnn_R_50_C4_1x_caffe2.yaml --min-image-size 256
Opening ZED Camera...
Mask enabled!
/home/dh-ununtu-64/anaconda3/envs/pytorch1/lib/python3.8/site-packages/maskrcnn_benchmark-0.1-py3.8-linux-x86_64.egg/maskrcnn_benchmark/structures/boxlist_ops.py:45: UserWarning: This overload of nonzero is deprecated:
 nonzero()
Consider using one of the following signatures instead:
 nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  keep = (
Traceback (most recent call last):
  File "zed_object_detection.py", line 293, in <module>
    main()
  File "zed_object_detection.py", line 281, in main
    composite = coco_demo.overlay_class_names(composite, prediction)
  File "/home/dh-ununtu-64/zedcamera/zed-pytorch/predictor.py", line 419, in overlay_class_names
    cv2.putText(image, s, (x, y), cv2.FONT_HERSHEY_SIMPLEX, .6, (255, 255, 255), 1)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'putText'
> Overload resolution failed:
>  - Can't parse 'org'. Sequence item with index 0 has a wrong type
>  - Can't parse 'org'. Sequence item with index 0 has a wrong type

template = "{}: {:.2f}"
        for box, score, label in zip(boxes, scores, labels):
            x, y = box[:2]
            x = x.to(dtype = torch.int)
            y = y.to(dtype = torch.int)
            #s = template.format(label, score)
            s = template.format(label, score)

            font = cv2.FONT_HERSHEY_SIMPLEX
            fontScale = 0.6
            fontColor = (255,255,255)
            org = (x, y)
            lineType = cv2.LINE_AA
            cv2.putText(image, s, (x, y), cv2.FONT_HERSHEY_SIMPLEX, .6, (255, 255, 255), 1)
            #cv2.putText(image, s, org, font, fontScale, fontColor, 1, lineType)
            #cv2.putText(image, s, org)

Does anyone know the reason?

**Comment by BCCWAI** [comment]
> (pytorch1) dh-ununtu-64@dhununtu64-HP-Z1-Entry-Tower-G5:~/zedcamera/zed-pytorch$ python zed_object_detection.py --config-file configs/caffe2/e2e_mask_rcnn_R_50_C4_1x_caffe2.yaml --min-image-size 256
> Opening ZED Camera...
> Mask enabled!
> /home/dh-ununtu-64/anaconda3/envs/pytorch1/lib/python3.8/site-packages/maskrcnn_benchmark-0.1-py3.8-linux-x86_64.egg/maskrcnn_benchmark/structures/boxlist_ops.py:45: UserWarning: This overload of nonzero is deprecated:
> nonzero()
> Consider using one of the following signatures instead:
> nonzero(*, bool as_tuple) (Triggered internally at /opt/conda/conda-bld/pytorch_1607370172916/work/torch/csrc/utils/python_arg_parser.cpp:882.)
> keep = (
> Traceback (most recent call last):
> File "zed_object_detection.py", line 293, in
> main()
> File "zed_object_detection.py", line 281, in main
> composite = coco_demo.overlay_class_names(composite, prediction)
> File "/home/dh-ununtu-64/zedcamera/zed-pytorch/predictor.py", line 419, in overlay_class_names
> cv2.putText(image, s, (x, y), cv2.FONT_HERSHEY_SIMPLEX, .6, (255, 255, 255), 1)
> cv2.error: OpenCV(4.5.3) 👎 error: (-5:Bad argument) in function 'putText'
> > Overload resolution failed:
> > * Can't parse 'org'. Sequence item with index 0 has a wrong type
> > * Can't parse 'org'. Sequence item with index 0 has a wrong type



> template = "{}: {:.2f}"
> for box, score, label in zip(boxes, scores, labels):
> x, y = box[:2]
> x = x.to(dtype = torch.int)
> y = y.to(dtype = torch.int)
> #s = template.format(label, score)
> s = template.format(label, score)
>         font = cv2.FONT_HERSHEY_SIMPLEX
>         fontScale = 0.6
>         fontColor = (255,255,255)
>         org = (x, y)
>         lineType = cv2.LINE_AA
>         cv2.putText(image, s, (x, y), cv2.FONT_HERSHEY_SIMPLEX, .6, (255, 255, 255), 1)
>         #cv2.putText(image, s, org, font, fontScale, fontColor, 1, lineType)
>         #cv2.putText(image, s, org)
> ```
> 
> Does anyone know the reason?

**Comment by obraun-sl** [comment]
Can you try with : 

```
x, y = box[:2]
x_i = int(x)
y_i = int(y)
#s = template.format(label, score)
s = template.format(label, score)
font = cv2.FONT_HERSHEY_SIMPLEX
fontScale = 0.6
fontColor = (255,255,255)
org = (x_i, y_i)
lineType = cv2.LINE_AA
cv2.putText(image, s, (x_i, y_i), cv2.FONT_HERSHEY_SIMPLEX, .6, (255, 255, 255), 1)
#cv2.putText(image, s, org, font, fontScale, fontColor, 1, lineType)
#cv2.putText(image, s, org)
```

It seems to complain that x/y had the wrong type (not int).

**Comment by BCCWAI** [comment]
@obraun-sl  Your solution works well，Thank you！
